format = "$directory$git_branch$nodejs$character"

[directory]
format = "[$path]($style) "
style = "bold cyan"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "red"

[nodejs]
format = "[⬢ $version]($style) "
style = "green"

[character]
success_symbol = "❯ "
error_symbol = "❯ "
